name: Auto Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      run: cargo build --release

    - name: Create Example Script
      shell: bash
      run: |
        cat <<EOF > example.k7sya
        #import "std.kh"

        main :: {
            var greeting: str = "Hello"
            var name: str = "World!"
            var version: i32 = 1
            

            var message: str = greeting ~ ", " ~ name
            
            println(message)
            println("Check (variables): " ~ version)
            
            var x: i32 = 10
            var y: i32 = 20
            var result: i32 = x + y
            
            println("check (math): " ~ result)
        }
        EOF

    - name: Automatic Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: dev
        prerelease: true
        name: Dev Version
        body: |
          Theres no information because of Automatic build
          Dont ignore example.k7sya maybe it helps for you to know k7Sya
        files: |
          target/release/k7sya_lite.exe
          example.k7sya
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
