name: Rust Build and Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # Используем windows-latest, чтобы получить .exe файл
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      # Собираем в режиме release для лучшей производительности
      run: cargo build --release 

    - name: Run tests
      run: cargo test --release --verbose

    - name: Upload Build Result
      # Этот шаг сохраняет файл, чтобы его можно было скачать
      uses: actions/upload-artifact@v4
      with:
        name: k7sya-binary-windows
        # Путь к твоему скомпилированному файлу
        path: target/release/k7sya_lite.exe
